<a href="https://colab.research.google.com/github/maicollGS/base-de-datos-challenge1-latam/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#Exploración Inicial

###1. Conocer el tamaño del dataset

In [23]:
tienda.shape

(2359, 12)

###2. Identificar las columnas

In [24]:
tienda.columns

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

###3. Información del conjunto de datos

In [21]:
tienda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

###4. Identificar que información contiene cada columna

In [30]:
tienda[["Producto", "Precio", "Calificación"]]

               Producto     Precio  Calificación
0     Asistente virtual   164300.0             4
1       Mesa de comedor   192300.0             1
2         Juego de mesa   209600.0             1
3            Microondas   757500.0             4
4      Silla de oficina   335200.0             5
...                 ...        ...           ...
2354          Iphone 15  1284400.0             1
2355          Impresora   282800.0             5
2356      Juego de mesa   122900.0             5
2357           Cama box   691300.0             1
2358         Smartwatch   195000.0             4

[2359 rows x 3 columns]

#1. Análisis de facturación

##Ingreso total por cada tienda

En este primer análisis, se calcula el ingreso total de cada tienda. Sumando los valores de la columna Precio de cada conjunto de datos de la tienda para estimar los ingresos.

In [82]:
def ingreso_tienda(dataset):
    total = dataset['Precio'].sum()
    print(f"Ingreso total de la tienda: ${total:,.2f}")

####Ingresos tienda 1

In [83]:
ingreso_total_tienda1 = ingreso_tienda(tienda)
ingreso_total_tienda1

Ingreso total de la tienda: $1,150,880,400.00

####Ingresos tienda 2

In [85]:
ingreso_total_tienda2 = ingreso_tienda(tienda2)
ingreso_total_tienda2

Ingreso total de la tienda: $1,116,343,500.00

####Ingresos tienda 3

In [86]:
ingreso_total_tienda3 = ingreso_tienda(tienda3)
ingreso_total_tienda3

Ingreso total de la tienda: $1,098,019,600.00

####Ingresos tienda 4

In [87]:
ingreso_total_tienda4 = ingreso_tienda(tienda4)
ingreso_total_tienda4

Ingreso total de la tienda: $1,038,375,700.00

In [88]:
def total_Agrupado(dato1, dato2, dato3, dato4, Columname):
  series = {'tienda1' : dato1,
            'tienda2' : dato2,
            'tienda3' : dato3,
            'tienda4' : dato4}
  return pd.Series(series, name = Columname)

In [89]:
Totales_Tiendas = total_Agrupado(ingreso_total_tienda1, ingreso_total_tienda2, ingreso_total_tienda3, ingreso_total_tienda4, 'Ingresos').astype(int)

Totales_Tiendas

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

# 2. Ventas por categoría

En este se calcula la cantidad de productos vendidos por categoría en cada tienda. La idea es agrupar los datos por categoría y contar el número de ventas de cada tipo, mostrando las categorías más populares de cada tienda.

#####Conteo categorias Tienda 1

In [63]:
conteo_categorias_Tienda1 = tienda['Categoría del Producto'].value_counts().sort_values(ascending=False).head(3)
print(conteo_categorias_Tienda1)

Categoría del Producto
Muebles         465
Electrónicos    448
Juguetes        324
Name: count, dtype: int64

####Conteo categorias Tienda 2

In [64]:
conteo_categorias_Tienda2 = tienda2['Categoría del Producto'].value_counts().sort_values(ascending=False).head(3)
print(conteo_categorias_Tienda2)

Categoría del Producto
Muebles         442
Electrónicos    422
Juguetes        313
Name: count, dtype: int64

####Conteo categorias Tienda 3

In [66]:
conteo_categorias_Tienda3 = tienda3['Categoría del Producto'].value_counts().sort_values(ascending=False).head(3)
print(conteo_categorias_Tienda3)

Categoría del Producto
Muebles         499
Electrónicos    451
Juguetes        315
Name: count, dtype: int64

####Conteo categorias Tienda 3

In [67]:
conteo_categorias_Tienda4 = tienda4['Categoría del Producto'].value_counts().sort_values(ascending=False).head(3)
print(conteo_categorias_Tienda4)

Categoría del Producto
Muebles         480
Electrónicos    451
Juguetes        338
Name: count, dtype: int64

# 3. Calificación promedio de la tienda

En este paso, se deben calcular las calificaciones promedio de los clientes para cada tienda. El objetivo es conocer la satisfacción del cliente con los productos vendidos.

####Calificación promedio de la tienda 1

In [69]:
Calificación_T1 = tienda["Calificación"].mean()
print(f"Calificación promedio tienda 1: {Calificación_T1:.2f}")

Calificación promedio tienda 1: 3.98

####Calificación promedio de la tienda 2

In [70]:
Calificación_T2 = tienda2["Calificación"].mean()
print(f"Calificación promedio tienda 2: {Calificación_T2:.2f}")

Calificación promedio tienda 1: 4.04

####Calificación promedio de la tienda 3

In [71]:
Calificación_T3 = tienda3["Calificación"].mean()
print(f"Calificación promedio tienda 3: {Calificación_T3:.2f}")

Calificación promedio tienda 3: 4.05

####Calificación promedio de la tienda 4

In [72]:
Calificación_T4 = tienda4["Calificación"].mean()
print(f"Calificación promedio tienda 4: {Calificación_T4:.2f}")

Calificación promedio tienda 4: 4.00

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda